##### 1. What is a Python library? Why do we use Python libraries?

##### **Ans :** Python library is a collection of modules that contain codes which can be used in different programs to perform takes in oprtimized way. We use python libraries because it makes out codes easier and simpler to understand. Many related methods and modules are contained in a same collection which can be reused at so many times. Hence it provides modularity, reusabilty and abstraction upto some extent.

##### 2. What is the difference between Numpy array and List?


##### **Ans :** Difference between Numpy array and List are - 
* Numpy array has continuous memory allocation while lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.
* Numpy array restricts the data object to be homogeneous in nature while list can contain different type of objects.
* Numpy array is much faster than list because Numpy array contains data values while list stores memory location of data values.
* Size of array is preknown in numpy array while size of list need not to be preknown in list

##### 3. Find the shape, size and dimension of the following array?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [3]:
# import the numpy library 
import numpy as np
# create an array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# get the size, shape and dimension of array
print("size of array -", arr.size)
print("shape of array -", arr.shape)
print("dimension of array -", arr.ndim)


size of array - 12
shape of array - (3, 4)
dimension of array - 2


##### 4. Write python code to access the first row of the following array?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [5]:
# import the numpy library 
import numpy as np
# create an array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# get first row of array
print("first row of array -", arr[0])



first row of array - [1 2 3 4]


##### 5. How do you access the element at the third row and fourth column from the given numpy array?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [6]:
# import the numpy library 
import numpy as np
# create an array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# get element at third row and fourth column from the array
print("element at third row and fourth column from the array -", arr[2][3])



element at third row and fourth column from the array - 12


##### 6. Write code to extract all odd-indexed elements from the given numpy array?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [7]:
# import the numpy library 
import numpy as np
# create an array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# get all odd indexed elements of array
for i in range(len(arr)):
    for j in range(len(arr[0])):
        if i%2==1 and j%2==1:
            print(arr[i][j])



6
8


##### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [19]:
# import the numpy library 
import numpy as np
lst = np.random.rand(3,3)
lst

array([[0.22345892, 0.81901155, 0.69732034],
       [0.46456032, 0.18190432, 0.53892724],
       [0.45816126, 0.20241388, 0.78693764]])

##### 8. Describe the difference between np.random.rand and np.random.randn?

##### **Ans :** randn generates numbers from a normal distribution with a mean of 0 and a standard deviation of 1, while rand generates numbers from a uniform distribution between 0 and 1.

##### 9. Write code to increase the dimension of the following array?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [22]:
# import the numpy library 
import numpy as np
# create an array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# increase the dimesion of array using resize
arr.resize(2,2,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

##### 10. How to transpose the following array in NumPy?
* [[1, 2, 3, 4]
* [5, 6, 7, 8],
* [9, 10, 11, 12]]

In [20]:
# import the numpy library 
import numpy as np
# create an array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# transpose the array
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

##### 11. Consider the following matrix:
* Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
* Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

##### Perform the following operation using Python:
* 1. Index wise multiplication

In [31]:
matA = [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
matB = [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
# zip each row of 1st matrics to the respective row of 2nd matrix, then zip the respective columns of thos rows and compute multiplication
index_wise_multiplication = [[(a*b) for a,b in zip(l1,l2)] for l1,l2 in zip(matA, matB)]
index_wise_multiplication

[[1, 4, 9, 16], [25, 36, 49, 64], [81, 100, 121, 144]]

* 2. matrix multiplication

In [36]:
# for each row of matA, zip each column of matB, then 
# then zip the elements of row of matA and column of matb
# then perform multiplication and addall values for that position 
multiplication_matrix = [[sum(a*b for a,b in zip(a_mat,b_mat)) for b_mat in zip(*matB)] for a_mat in matA]
multiplication_matrix

[[38, 44, 50, 56], [98, 116, 134, 152], [158, 188, 218, 248]]

* 3. Add both matrix

In [37]:
# zip each row of 1st matrics to the respective row of 2nd matrix, then zip the respective columns of thos rows and compute addition
addition = [[(a+b) for a,b in zip(l1,l2)] for l1,l2 in zip(matA, matB)]
addition

[[2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24]]

* 4. Subtract matrix B from Matrix A

In [40]:
# zip each row of 1st matrics to the respective row of 2nd matrix, then zip the respective columns of thos rows and compute substraction
substraction = [[(b-a) for a,b in zip(l1,l2)] for l1,l2 in zip(matA, matB)]
substraction

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

* 5. Divide matrix B by A

In [41]:
# zip each row of 1st matrics to the respective row of 2nd matrix, then zip the respective columns of thos rows and compute division
division = [[(b/a) for a,b in zip(l1,l2)] for l1,l2 in zip(matA, matB)]
division

[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]

##### 12. Which function in Numpy can be used to swap the byte order of an array?

##### **Ans :** np.ndarray.byteswap()

##### 13. What is the significance of the np.linalg.inv function?

##### **Ans :** numpy. linalg. inv() function is used to calculate the inverse of a matrix.

##### 14. What does the np.reshape function do, and how is it used?

##### **Ans :** np.reshape() is used to change the shape of array.It can be used as -

In [44]:
# import the numpy library 
import numpy as np
# create an array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# changing shape from 3X4 to 2X6
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

##### 15. What is broadcasting in Numpy?

##### **Ans :** In broadcasting, numpy treats arrays with different shapes during arithmetic operations. The smaller array is broadcast to same shape as of larger array so that they can be compatible to each other during operations.