In [1]:
import numpy as np #2005 by Travis Oliphant

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
l = [1,2,3,4,5,6]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr.ndim

1

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
mat = np.matrix(l)
mat

matrix([[1, 2, 3, 4, 5, 6]])

In [12]:
np.array([[1,2,3],[3,4,5],[5,6,7]])

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [15]:
np.asarray(mat)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5, 6]])

In [17]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [20]:
np.array(t)
np.asarray(t)
np.asanyarray(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.fromfunction(lambda i,j : i*j , (3,3))
# it works on index

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [25]:
iterable = [i*i for i in range(5)]
iterable

[0, 1, 4, 9, 16]

In [26]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [32]:

np.fromstring('23 34 67',dtype=int, sep = ' ')

array([23, 34, 67])

In [33]:
np.fromstring('Suhani,Ajay,Anwesha', sep = ',')

C:\Users\Dell\AppData\Local\Temp\ipykernel_19436\4232903791.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Suhani,Ajay,Anwesha', sep = ',')


array([], dtype=float64)

In [37]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr.size  # gives count

10

In [38]:
arr.shape  # gives shape - (row, col)

(2, 5)

In [39]:
arr.dtype # gives datatype of elements

dtype('int32')

In [40]:
list(range(5))

[0, 1, 2, 3, 4]

In [44]:
arange_list = list(np.arange(1,10,2))
arange_list

[1, 3, 5, 7, 9]

In [45]:
linspace_list = np.linspace(1,5,10)
linspace_list

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [48]:
logspace_list = np.logspace(1,5,10, base=3)
# it is same as 
# logspace_list[i] = pow(base, list(np.linspace(1,5,10))[i])
# pow(3,1.44444)

4.888470797557861

In [50]:
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [51]:
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
arr3 = np.zeros((2, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
arr = np.ones((3,4))

In [55]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [65]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [57]:
l = [1,2,3]
l = np.array(l)
print(l)
l.dtype

[1 2 3]


dtype('int32')

In [59]:
l = [1,2,3,'abc']
l = np.array(l)
print(l)
l.dtype
# <U11 is a string type

['1' '2' '3' 'abc']


dtype('<U11')

In [61]:
import numpy as np

# Example matrices
A = np.array([[1, 2], [0, 4]])
B = np.array([[5, 6], [7, 8]])

# Using np.dot for matrix multiplication
matrix_product = np.dot(A, B)
print("Matrix product using np.dot:\n", matrix_product)

# Using @ operator for matrix multiplication (Python 3.5 and later)
matrix_product = A @ B
print("Matrix product using @ operator:\n", matrix_product)

Matrix product using np.dot:
 [[19 22]
 [28 32]]
Matrix product using @ operator:
 [[19 22]
 [28 32]]


In [64]:
A = np.array([[1,2,0,4,5],[3,4,0,5,4],[2,0,6,23,76]])
np.count_nonzero(A)

12

In [1]:
import numpy as np
import time

# Generate two random NumPy arrays with one million elements each
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)

# Measure time for the vectorized version using np.dot
start_time_vectorized = time.time()
result_vectorized = np.dot(array1, array2)
end_time_vectorized = time.time()

# Print the time taken for the vectorized version
print("Time taken for vectorized calculation: " + str(1000 * (end_time_vectorized - start_time_vectorized)) + " milliseconds")

# Reset result_vectorized to 0
result_vectorized = 0

# Measure time for the version using a for loop
start_time_for_loop = time.time()
for index in range(1000000):
    result_vectorized += array1[index] * array2[index]
end_time_for_loop = time.time()

# Print the time taken for the for loop version
print("Time taken for calculation using a for loop: " + str(1000 * (end_time_for_loop - start_time_for_loop)) + " milliseconds")


Time taken for vectorized calculation: 87.42165565490723 milliseconds
Time taken for calculation using a for loop: 1047.6405620574951 milliseconds
