In [1]:
import numpy as np #2005 by Travis Oliphant

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
l = [1,2,3,4,5,6]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr.ndim

1

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
mat = np.matrix(l)
mat

matrix([[1, 2, 3, 4, 5, 6]])

In [12]:
np.array([[1,2,3],[3,4,5],[5,6,7]])

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [15]:
np.asarray(mat)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5, 6]])

In [17]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [20]:
np.array(t)
np.asarray(t)
np.asanyarray(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.fromfunction(lambda i,j : i*j , (3,3))
# it works on index

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [25]:
iterable = [i*i for i in range(5)]
iterable

[0, 1, 4, 9, 16]

In [26]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [32]:

np.fromstring('23 34 67',dtype=int, sep = ' ')

array([23, 34, 67])

In [33]:
np.fromstring('Suhani,Ajay,Anwesha', sep = ',')

C:\Users\Dell\AppData\Local\Temp\ipykernel_19436\4232903791.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Suhani,Ajay,Anwesha', sep = ',')


array([], dtype=float64)

In [37]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr.size  # gives count

10

In [38]:
arr.shape  # gives shape - (row, col)

(2, 5)

In [39]:
arr.dtype # gives datatype of elements

dtype('int32')

In [40]:
list(range(5))

[0, 1, 2, 3, 4]

In [44]:
arange_list = list(np.arange(1,10,2))
arange_list

[1, 3, 5, 7, 9]

In [45]:
linspace_list = np.linspace(1,5,10)
linspace_list

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [48]:
logspace_list = np.logspace(1,5,10, base=3)
# it is same as 
# logspace_list[i] = pow(base, list(np.linspace(1,5,10))[i])
# pow(3,1.44444)

4.888470797557861

In [50]:
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [51]:
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
arr3 = np.zeros((2, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
arr = np.ones((3,4))

In [55]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [65]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [57]:
l = [1,2,3]
l = np.array(l)
print(l)
l.dtype

[1 2 3]


dtype('int32')

In [59]:
l = [1,2,3,'abc']
l = np.array(l)
print(l)
l.dtype
# <U11 is a string type

['1' '2' '3' 'abc']


dtype('<U11')

In [61]:
import numpy as np

# Example matrices
A = np.array([[1, 2], [0, 4]])
B = np.array([[5, 6], [7, 8]])

# Using np.dot for matrix multiplication
matrix_product = np.dot(A, B)
print("Matrix product using np.dot:\n", matrix_product)

# Using @ operator for matrix multiplication (Python 3.5 and later)
matrix_product = A @ B
print("Matrix product using @ operator:\n", matrix_product)

Matrix product using np.dot:
 [[19 22]
 [28 32]]
Matrix product using @ operator:
 [[19 22]
 [28 32]]


In [64]:
A = np.array([[1,2,0,4,5],[3,4,0,5,4],[2,0,6,23,76]])
np.count_nonzero(A)

12

In [1]:
import numpy as np
import time

# Generate two random NumPy arrays with one million elements each
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)

# Measure time for the vectorized version using np.dot
start_time_vectorized = time.time()
result_vectorized = np.dot(array1, array2)
end_time_vectorized = time.time()

# Print the time taken for the vectorized version
print("Time taken for vectorized calculation: " + str(1000 * (end_time_vectorized - start_time_vectorized)) + " milliseconds")

# Reset result_vectorized to 0
result_vectorized = 0

# Measure time for the version using a for loop
start_time_for_loop = time.time()
for index in range(1000000):
    result_vectorized += array1[index] * array2[index]
end_time_for_loop = time.time()

# Print the time taken for the for loop version
print("Time taken for calculation using a for loop: " + str(1000 * (end_time_for_loop - start_time_for_loop)) + " milliseconds")


Time taken for vectorized calculation: 87.42165565490723 milliseconds
Time taken for calculation using a for loop: 1047.6405620574951 milliseconds


In [1]:
import numpy as np

In [2]:
data = np.array([[1],[2],[3]])

In [3]:
data.ndim

2

In [4]:
np.squeeze(data)

array([1, 2, 3])

In [5]:
np.expand_dims(data, axis=1)

array([[[1]],

       [[2]],

       [[3]]])

In [6]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [7]:
np.repeat(data,2, axis = 1)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [8]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [13]:
np.roll([1,2,3], 2 , axis=0)

array([2, 3, 1])

In [14]:
np.roll(data,-2)

array([[3],
       [1],
       [2]])

In [15]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [17]:
arr1

array([[6, 7, 8, 5],
       [3, 4, 7, 3],
       [4, 1, 5, 3]])

In [18]:
arr2

array([[4, 3, 3, 5],
       [3, 8, 5, 4],
       [3, 4, 9, 8]])

### Arithmatic Function

In [19]:
arr1+arr2

array([[10, 10, 11, 10],
       [ 6, 12, 12,  7],
       [ 7,  5, 14, 11]])

In [20]:
arr1-arr2

array([[ 2,  4,  5,  0],
       [ 0, -4,  2, -1],
       [ 1, -3, -4, -5]])

In [21]:
arr1*arr2

array([[24, 21, 24, 25],
       [ 9, 32, 35, 12],
       [12,  4, 45, 24]])

In [22]:
arr1/arr2

array([[1.5       , 2.33333333, 2.66666667, 1.        ],
       [1.        , 0.5       , 1.4       , 0.75      ],
       [1.33333333, 0.25      , 0.55555556, 0.375     ]])

In [23]:
arr1**arr2

array([[   1296,     343,     512,    3125],
       [     27,   65536,   16807,      81],
       [     64,       1, 1953125,    6561]])

In [24]:
arr1 > arr2

array([[ True,  True,  True, False],
       [False, False,  True, False],
       [ True, False, False, False]])

In [25]:
arr1

array([[6, 7, 8, 5],
       [3, 4, 7, 3],
       [4, 1, 5, 3]])

In [26]:
~arr1

array([[-7, -8, -9, -6],
       [-4, -5, -8, -4],
       [-5, -2, -6, -4]])

### string Function

In [27]:
arr = np.array(["pw", "skills"])

In [28]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [29]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [30]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

### Mathematical Function

In [31]:
np.cos(arr1)

array([[ 0.96017029,  0.75390225, -0.14550003,  0.28366219],
       [-0.9899925 , -0.65364362,  0.75390225, -0.9899925 ],
       [-0.65364362,  0.54030231,  0.28366219, -0.9899925 ]])

In [32]:
np.sin(arr1)

array([[-0.2794155 ,  0.6569866 ,  0.98935825, -0.95892427],
       [ 0.14112001, -0.7568025 ,  0.6569866 ,  0.14112001],
       [-0.7568025 ,  0.84147098, -0.95892427,  0.14112001]])

In [33]:
np.tan(arr1)

array([[-0.29100619,  0.87144798, -6.79971146, -3.38051501],
       [-0.14254654,  1.15782128,  0.87144798, -0.14254654],
       [ 1.15782128,  1.55740772, -3.38051501, -0.14254654]])

In [34]:
np.log10(arr1)

array([[0.77815125, 0.84509804, 0.90308999, 0.69897   ],
       [0.47712125, 0.60205999, 0.84509804, 0.47712125],
       [0.60205999, 0.        , 0.69897   , 0.47712125]])

In [35]:
np.exp(arr1)

array([[4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 1.48413159e+02],
       [2.00855369e+01, 5.45981500e+01, 1.09663316e+03, 2.00855369e+01],
       [5.45981500e+01, 2.71828183e+00, 1.48413159e+02, 2.00855369e+01]])

In [36]:
np.power(arr1,3)

array([[216, 343, 512, 125],
       [ 27,  64, 343,  27],
       [ 64,   1, 125,  27]], dtype=int32)

In [38]:
np.mean(arr1)

4.666666666666667

In [39]:
np.median(arr1)

4.5

In [40]:
np.min(arr1), np.max(arr1)

(1, 8)

In [41]:
np.var(arr1)

3.8888888888888893

In [42]:
np.std(arr1)

1.9720265943665387

In [43]:
np.power(arr1, arr2)

array([[   1296,     343,     512,    3125],
       [     27,   65536,   16807,      81],
       [     64,       1, 1953125,    6561]])

In [44]:
np.mod(arr1, arr2)

array([[2, 1, 2, 0],
       [0, 4, 2, 3],
       [1, 1, 5, 3]])

In [45]:
np.sqrt(arr1)

array([[2.44948974, 2.64575131, 2.82842712, 2.23606798],
       [1.73205081, 2.        , 2.64575131, 1.73205081],
       [2.        , 1.        , 2.23606798, 1.73205081]])

### sort search

In [46]:
arr = np.array([5, 6, 1, 2])

In [47]:
np.sort(arr1)

array([[5, 6, 7, 8],
       [3, 3, 4, 7],
       [1, 3, 4, 5]])

In [61]:
arr = np.array([5, 6,100, 200, 1, 2, 8, 9])
np.sort(arr)

array([  1,   2,   5,   6,   8,   9, 100, 200])

In [62]:
np.searchsorted(arr, 5) 

6

In [70]:
arr1 = np.array([0, 1, 2,0, 5,3, 0, 4])
np.count_nonzero(arr1)

5

In [71]:
np.where(arr1 > 0) #returns indexs

(array([1, 2, 4, 5, 7], dtype=int64),)

In [72]:
np.extract(arr1 > 0, arr1) #returns values array

array([1, 2, 5, 3, 4])

### Numpy Linear algebra

In [75]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])
arr1 @ arr2  #matrix multiplication

array([[14, 21],
       [24, 37]])

In [76]:
a  = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])
b = np.array([16, -8, 0])

In [77]:
np.linalg.solve(a, b)

array([0.90162081, 2.89483603, 1.88465888])

In [78]:
np.linalg.det(arr1) # determinant of matrix

-2.0

In [79]:
np.linalg.inv(arr1) #inverse of matrix

array([[-2.5,  1.5],
       [ 2. , -1. ]])